Add an example for LWR iiwa with Xtion/Kinect
IFL-CAMP/easy_handeye pull request #70
Opened 2020-12-04 13:55 UTC by lyh458

Thank you for your awesome work!
This is an example for LWR iiwa with Xtion/Kinect, which have been verified on real robot.

2020-12-06 13:31 UTC, marcoesposito1988 requested changes
Hey @lyh458,

thanks a lot, this may be very helpful for new users!

I would suggest to remove the default values for the argument regarding the marker ID and size, because if a new user prints some different marker, this will otherwise silently fail. Removing the default forces the user to enter the correct values. What do you think?

2020-12-06 13:31 UTC, marcoesposito1988 commented on docs/example_launch/iiwa_kinect_xtion_calibration.launch
> +    <arg name="marker_size" default="0.05" doc="Size of the ArUco marker used, in meters" />
```suggestion
    <arg name="marker_size" doc="Size of the ArUco marker used, in meters" />
```

2020-12-06 13:31 UTC, marcoesposito1988 commented on docs/example_launch/iiwa_kinect_xtion_calibration.launch
> +    <arg name="marker_id" default="100" doc="The ID of the ArUco marker used" />
```suggestion
    <arg name="marker_id" doc="The ID of the ArUco marker used" />
```

2020-12-06 13:59 UTC, lyh458 commented
Yes, you are right!

2020-12-07 13:18 UTC, marcoesposito1988 approved these changes

2020-12-07 13:18 UTC, merged

2020-12-07 13:18 UTC, marcoesposito1988 commented
Great, thanks a lot for your contribution! Further help is welcome anytime :)